Prefixed VarNames (#119)
Closes #108. With this PR:

```julia
using FlexiChains, Turing, Random
using FlexiChains: Prefixed

@model inner() = y ~ Normal()
chn1 = sample(Xoshiro(468), inner(), Prior(), 3; chain_type=VNChain)

@model function outer()
    a ~ to_submodel(inner())
end
chn2 = sample(Xoshiro(468), outer(), Prior(), 3; chain_type=VNChain)

chn1[@varname(y)]            # OK because no prefix
chn2[@varname(y)]            # errors because prefixed
chn1[Prefixed(@varname(y))]  # OK
chn2[Prefixed(@varname(y))]  # OK
```

```julia
julia> chn1[@varname(y)]
┌ 3×1 DimArray{Float64, 2} Parameter(y) ┐
├───────────────────────────────────────┴───────────── dims ┐
  ↓ iter Sampled{Int64} 1:3 ForwardOrdered Regular Points,
  → chain Sampled{Int64} 1:1 ForwardOrdered Regular Points
└───────────────────────────────────────────────────────────┘
 ↓ →   1
 1     0.0720089
 2    -0.0740438
 3     0.632776

julia> chn2[@varname(y)]
ERROR: KeyError: key y not found
Stacktrace:
 [1] _getindex_optic_and_vn
   @ ~/ppl/fc/src/varname.jl:54 [inlined]
 [2]
_get_raw_data(cs::VNChain{FlexiChains.FlexiChainMetadata{…}}, vn_param::FlexiChains.Parameter{VarName{…}})
   @ FlexiChains ~/ppl/fc/src/varname.jl:68
 [3] getindex(fchain::VNChain{…}, vn::VarName{…}; iter::Function, chain::Function)
   @ FlexiChains ~/ppl/fc/src/varname.jl:96
 [4] getindex(fchain::VNChain{FlexiChains.FlexiChainMetadata{…}}, vn::VarName{:y, AbstractPPL.Iden})
   @ FlexiChains ~/ppl/fc/src/varname.jl:93
 [5] top-level scope
   @ REPL[30]:1
Some type information was truncated. Use `show(err)` to see complete types.

julia> chn1[Prefixed(@varname(y))]
┌ 3×1 DimArray{Float64, 2} Parameter(y) ┐
├───────────────────────────────────────┴───────────── dims ┐
  ↓ iter Sampled{Int64} 1:3 ForwardOrdered Regular Points,
  → chain Sampled{Int64} 1:1 ForwardOrdered Regular Points
└───────────────────────────────────────────────────────────┘
 ↓ →   1
 1     0.0720089
 2    -0.0740438
 3     0.632776

julia> chn2[Prefixed(@varname(y))]
┌ 3×1 DimArray{Float64, 2} Parameter(a.y) ┐
├─────────────────────────────────────────┴─────────── dims ┐
  ↓ iter Sampled{Int64} 1:3 ForwardOrdered Regular Points,
  → chain Sampled{Int64} 1:1 ForwardOrdered Regular Points
└───────────────────────────────────────────────────────────┘
 ↓ →   1
 1     0.0720089
 2    -0.0740438
 3     0.632776
```

@seabbs: I finally got around to implementing this. Two questions:

1. Is this a correct representation of what you wanted?

2. How much do you care about even more fine-grained-ness? For example,
if the chain stores a vector `x`, then FlexiChains lets you index into
`chn[@varname(x[1])]`. Would it be essential to have
`chn[Prefixed(@varname(x[1]))]` to also search for e.g. vectors `a.x`
and give you the first element of it, or is that just a nice-to-have?
I'm probably going to implement it either way but just curious as to how
important it is.

----

TODO

- [x] Fix for complex varnames
- [x] Tests
- [x] Docs