Re-export Begin/End; document + add error hint (#250)
Closes #153 properly

Now when someone tries to index with `begin` / `end` they get a friendly
error hint:

```julia
julia> chain[iter=1:end]
ERROR: MethodError: no method matching lastindex(::FlexiChains.SymChain{FlexiChains.FlexiChainMetadata{…}})
The function `lastindex` exists, but no method is defined for this combination of argument types.

    Indexing into FlexiChains objects with `begin` or `end` does not work; please use `Begin` and `End` instead, which are equivalent.

Closest candidates are:
  lastindex(::Any, ::Any)
   @ Base abstractarray.jl:427
  lastindex(::Base64.Buffer)
   @ Base64 ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/Base64/src/buffer.jl:19
  lastindex(::Markdown.MD)
   @ Markdown ~/.julia/juliaup/julia-1.12.6+0.aarch64.apple.darwin14/Julia-1.12.app/Contents/Resources/julia/share/julia/stdlib/v1.12/Markdown/src/parse/parse.jl:33
```